version: '2.1'

orbs:
  ruby: circleci/ruby@1.1.0

workflows: 
  test-deploy:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.2
    steps:
      - checkout
      - ruby/install-deps




# # from this page: https://circleci.com/developer/ja/orbs/orb/circleci/ruby
# orbs:
#   ruby: circleci/ruby@2.0.1
# jobs:
#   build:
#     docker:
#       - image: cimg/ruby:3.2.2
#     steps:
#       - checkout
#       - ruby/install-deps
#   checking:
#     docker:
#       - image: cimg/ruby:3.2.2
#     steps:
#       - checkout
#       - ruby/install-deps
#       - ruby/rubocop-check:
#           format: progress
#           label: Inspecting with Rubocop
#   test:
#     docker:
#       - image: cimg/ruby:3.2.2
#       - environment:
#           POSTGRES_DB: hotel_pro_postgresql_test
#           POSTGRES_PASSWORD: ''
#           POSTGRES_USER: circleci-demo-ruby
#         image: circleci/postgres:14.6
#     environment:
#       BUNDLE_JOBS: '3'
#       BUNDLE_RETRY: '3'
#       PGHOST: 127.0.0.1
#       PGPASSWORD: ''
#       PGUSER: hotel_pro
#       RAILS_ENV: test
#     parallelism: 3
#     steps:
#       - checkout
#       - ruby/install-deps
#       - run:
#           command: dockerize -wait tcp://localhost:5432 -timeout 1m
#           name: Wait for DB
#       - run:
#           command: bundle exec rails db:schema:load --trace
#           name: Database setup
#       - ruby/rspec-test:
#           include: spec/**/*_spec.rb
# workflows:
#   build_and_test:
#     jobs:
#       - build
#       - checking
#       - test:
#           requires:
#             - build


# from hackernoon article: https://hackernoon.com/setting-up-ruby-on-rails-on-github-using-circleci-a-how-to-guide-4nal328a
# executors:
#   default:
#     working_directory: ~/hotel_pro
#     docker:
#       - image: circleci/ruby:3.2.2
#         environment:
#           BUNDLE_JOBS: 3
#           BUNDLE_PATH: vendor/bundle
#           BUNDLE_RETRY: 3
#           BUNDLER_VERSION: 2.4.17
#           RAILS_ENV: test
#           DB_HOST: 127.0.0.1
#           PG_HOST: 127.0.0.1
#           PGUSER: hotel_pro
#       - image: circleci/postgres:14.6
#         environment:
#           POSTGRES_DB: hotel_pro_postgresql_test
#           POSTGRES_USER: hotel_pro

# commands:
#   configure_bundler:
#     description: Configure bundler
#     steps:
#       - run:
#           name: Configure bundler
#           command: |
#             echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
#             source $BASH_ENV
#             gem install bundler

# jobs:
#   build:
#     executor: default
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - hotel_pro-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#             - hotel_pro-
#       - configure_bundler
#       - run:
#           name: Install bundle
#           command: bundle install
#       - run:
#           name: Wait for DB
#           command: dockerize -wait tcp://127.0.0.1:5432 -timeout 1m
#       - run:
#           name: Setup DB
#           command: bundle exec rails db:create db:schema:load --trace
#       - run: 
#           name: RSpec
#           commands: |
#             bundle exec rspec --profile 10 \
#                               --format progress
#       - store_artifacts:
#           path: coverage        
#       - save_cache:
#           key: hotel_pro-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
#           paths:
#             - vendor/bundle
#       - persist_to_workspace:
#           root: ~/
#           paths:
#             - ./hotel_pro
  
# # rubocop:
# #   executor: default
# #   steps:
# #     - attach_workspace:
# #         at: ~/
# #     - configure_bundler
#     - run:
#         name: Rubocop
#         command: bundle exec rubocop

# workflows:
#   version: 2
#   integration:
#     jobs:
#       - build
#       # - rubocop:
#       #     requires:
#       #       - build