default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: hotel_pro_development

test:
  <<: *default
  database: hotel_pro_test

production:
  <<: *default
  database: hotel_pro_production
  username: hotel_pro
  password: <%= ENV["HOTEL_PRO_DATABASE_PASSWORD"] %>
